module "iam_iam-user" {
  source                           = "terraform-aws-modules/iam/aws//modules/iam-user"
  version                          = "6.6.0"
  access_key_status                = var.access_key_status
  create                           = var.create
  create_access_key                = var.create_access_key
  create_inline_policy             = var.create_inline_policy
  create_login_profile             = var.create_login_profile
  create_ssh_key                   = var.create_ssh_key
  force_destroy                    = var.force_destroy
  inline_policy_permissions        = var.inline_policy_permissions
  name                             = var.name
  override_inline_policy_documents = var.override_inline_policy_documents
  password_length                  = var.password_length
  password_reset_required          = var.password_reset_required
  path                             = var.path
  permissions_boundary             = var.permissions_boundary
  pgp_key                          = var.pgp_key
  policies                         = var.policies
  source_inline_policy_documents   = var.source_inline_policy_documents
  ssh_key_encoding                 = var.ssh_key_encoding
  ssh_public_key                   = var.ssh_public_key
  tags                             = var.tags
}
