terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}

provider "aws" {
  region = var.region
}

module "eks_eks-managed-node-group" {
  source                                 = "terraform-aws-modules/eks/aws//modules/eks-managed-node-group"
  version                                = "21.24.0"
  account_id                             = var.account_id
  ami_id                                 = var.ami_id
  ami_release_version                    = var.ami_release_version
  ami_type                               = var.ami_type
  block_device_mappings                  = var.block_device_mappings
  bootstrap_extra_args                   = var.bootstrap_extra_args
  capacity_reservation_specification     = var.capacity_reservation_specification
  capacity_type                          = var.capacity_type
  cloudinit_post_nodeadm                 = var.cloudinit_post_nodeadm
  cloudinit_pre_nodeadm                  = var.cloudinit_pre_nodeadm
  cluster_auth_base64                    = var.cluster_auth_base64
  cluster_endpoint                       = var.cluster_endpoint
  cluster_ip_family                      = var.cluster_ip_family
  cluster_name                           = var.cluster_name
  cluster_primary_security_group_id      = var.cluster_primary_security_group_id
  cluster_service_cidr                   = var.cluster_service_cidr
  cpu_options                            = var.cpu_options
  create                                 = var.create
  create_iam_role                        = var.create_iam_role
  create_iam_role_policy                 = var.create_iam_role_policy
  create_launch_template                 = var.create_launch_template
  create_placement_group                 = var.create_placement_group
  create_security_group                  = var.create_security_group
  credit_specification                   = var.credit_specification
  desired_size                           = var.desired_size
  disable_api_termination                = var.disable_api_termination
  disk_size                              = var.disk_size
  ebs_optimized                          = var.ebs_optimized
  efa_indices                            = var.efa_indices
  enable_bootstrap_user_data             = var.enable_bootstrap_user_data
  enable_efa_only                        = var.enable_efa_only
  enable_efa_support                     = var.enable_efa_support
  enable_monitoring                      = var.enable_monitoring
  enclave_options                        = var.enclave_options
  force_update_version                   = var.force_update_version
  iam_role_additional_policies           = var.iam_role_additional_policies
  iam_role_arn                           = var.iam_role_arn
  iam_role_attach_cni_policy             = var.iam_role_attach_cni_policy
  iam_role_description                   = var.iam_role_description
  iam_role_name                          = var.iam_role_name
  iam_role_path                          = var.iam_role_path
  iam_role_permissions_boundary          = var.iam_role_permissions_boundary
  iam_role_policy_statements             = var.iam_role_policy_statements
  iam_role_tags                          = var.iam_role_tags
  iam_role_use_name_prefix               = var.iam_role_use_name_prefix
  instance_market_options                = var.instance_market_options
  instance_types                         = var.instance_types
  kernel_id                              = var.kernel_id
  key_name                               = var.key_name
  kubernetes_version                     = var.kubernetes_version
  labels                                 = var.labels
  launch_template_default_version        = var.launch_template_default_version
  launch_template_description            = var.launch_template_description
  launch_template_id                     = var.launch_template_id
  launch_template_name                   = var.launch_template_name
  launch_template_tags                   = var.launch_template_tags
  launch_template_use_name_prefix        = var.launch_template_use_name_prefix
  launch_template_version                = var.launch_template_version
  license_specifications                 = var.license_specifications
  maintenance_options                    = var.maintenance_options
  max_size                               = var.max_size
  metadata_options                       = var.metadata_options
  min_size                               = var.min_size
  name                                   = var.name
  network_interfaces                     = var.network_interfaces
  network_performance_options            = var.network_performance_options
  node_repair_config                     = var.node_repair_config
  partition                              = var.partition
  placement                              = var.placement
  post_bootstrap_user_data               = var.post_bootstrap_user_data
  pre_bootstrap_user_data                = var.pre_bootstrap_user_data
  private_dns_name_options               = var.private_dns_name_options
  ram_disk_id                            = var.ram_disk_id
  region                                 = var.region
  remote_access                          = var.remote_access
  security_group_description             = var.security_group_description
  security_group_egress_rules            = var.security_group_egress_rules
  security_group_ingress_rules           = var.security_group_ingress_rules
  security_group_name                    = var.security_group_name
  security_group_tags                    = var.security_group_tags
  security_group_use_name_prefix         = var.security_group_use_name_prefix
  subnet_ids                             = var.subnet_ids
  tag_specifications                     = var.tag_specifications
  tags                                   = var.tags
  taints                                 = var.taints
  timeouts                               = var.timeouts
  update_config                          = var.update_config
  update_launch_template_default_version = var.update_launch_template_default_version
  use_custom_launch_template             = var.use_custom_launch_template
  use_latest_ami_release_version         = var.use_latest_ami_release_version
  use_name_prefix                        = var.use_name_prefix
  user_data_template_path                = var.user_data_template_path
  vpc_security_group_ids                 = var.vpc_security_group_ids
}
