module "cloudwatch_log-account-policy" {
  source                                        = "terraform-aws-modules/cloudwatch/aws//modules/log-account-policy"
  version                                       = "5.7.2"
  audit_statement_sid                           = var.audit_statement_sid
  create                                        = var.create
  create_log_data_protection_policy             = var.create_log_data_protection_policy
  data_identifiers                              = var.data_identifiers
  deidentify_statement_sid                      = var.deidentify_statement_sid
  findings_destination_cloudwatch_log_group     = var.findings_destination_cloudwatch_log_group
  findings_destination_firehose_delivery_stream = var.findings_destination_firehose_delivery_stream
  findings_destination_s3_bucket                = var.findings_destination_s3_bucket
  log_account_policy_name                       = var.log_account_policy_name
  log_account_policy_scope                      = var.log_account_policy_scope
  log_account_policy_selection_criteria         = var.log_account_policy_selection_criteria
  log_account_policy_type                       = var.log_account_policy_type
  log_data_protection_description               = var.log_data_protection_description
  log_data_protection_policy_name               = var.log_data_protection_policy_name
  policy_document                               = var.policy_document
}
