terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}

provider "aws" {
  region = var.region
}

module "eks_self-managed-node-group" {
  source                                 = "terraform-aws-modules/eks/aws//modules/self-managed-node-group"
  version                                = "18.10.2"
  ami_id                                 = var.ami_id
  availability_zones                     = var.availability_zones
  block_device_mappings                  = var.block_device_mappings
  bootstrap_extra_args                   = var.bootstrap_extra_args
  capacity_rebalance                     = var.capacity_rebalance
  capacity_reservation_specification     = var.capacity_reservation_specification
  cluster_auth_base64                    = var.cluster_auth_base64
  cluster_endpoint                       = var.cluster_endpoint
  cluster_ip_family                      = var.cluster_ip_family
  cluster_name                           = var.cluster_name
  cluster_security_group_id              = var.cluster_security_group_id
  cluster_version                        = var.cluster_version
  cpu_options                            = var.cpu_options
  create                                 = var.create
  create_iam_instance_profile            = var.create_iam_instance_profile
  create_launch_template                 = var.create_launch_template
  create_schedule                        = var.create_schedule
  create_security_group                  = var.create_security_group
  credit_specification                   = var.credit_specification
  default_cooldown                       = var.default_cooldown
  delete_timeout                         = var.delete_timeout
  desired_size                           = var.desired_size
  disable_api_termination                = var.disable_api_termination
  ebs_optimized                          = var.ebs_optimized
  elastic_gpu_specifications             = var.elastic_gpu_specifications
  elastic_inference_accelerator          = var.elastic_inference_accelerator
  enable_monitoring                      = var.enable_monitoring
  enabled_metrics                        = var.enabled_metrics
  enclave_options                        = var.enclave_options
  force_delete                           = var.force_delete
  health_check_grace_period              = var.health_check_grace_period
  health_check_type                      = var.health_check_type
  hibernation_options                    = var.hibernation_options
  iam_instance_profile_arn               = var.iam_instance_profile_arn
  iam_role_additional_policies           = var.iam_role_additional_policies
  iam_role_attach_cni_policy             = var.iam_role_attach_cni_policy
  iam_role_description                   = var.iam_role_description
  iam_role_name                          = var.iam_role_name
  iam_role_path                          = var.iam_role_path
  iam_role_permissions_boundary          = var.iam_role_permissions_boundary
  iam_role_tags                          = var.iam_role_tags
  iam_role_use_name_prefix               = var.iam_role_use_name_prefix
  initial_lifecycle_hooks                = var.initial_lifecycle_hooks
  instance_initiated_shutdown_behavior   = var.instance_initiated_shutdown_behavior
  instance_market_options                = var.instance_market_options
  instance_refresh                       = var.instance_refresh
  instance_type                          = var.instance_type
  kernel_id                              = var.kernel_id
  key_name                               = var.key_name
  launch_template_default_version        = var.launch_template_default_version
  launch_template_description            = var.launch_template_description
  launch_template_name                   = var.launch_template_name
  launch_template_tags                   = var.launch_template_tags
  launch_template_use_name_prefix        = var.launch_template_use_name_prefix
  launch_template_version                = var.launch_template_version
  license_specifications                 = var.license_specifications
  max_instance_lifetime                  = var.max_instance_lifetime
  max_size                               = var.max_size
  metadata_options                       = var.metadata_options
  metrics_granularity                    = var.metrics_granularity
  min_elb_capacity                       = var.min_elb_capacity
  min_size                               = var.min_size
  mixed_instances_policy                 = var.mixed_instances_policy
  name                                   = var.name
  network_interfaces                     = var.network_interfaces
  placement                              = var.placement
  placement_group                        = var.placement_group
  platform                               = var.platform
  post_bootstrap_user_data               = var.post_bootstrap_user_data
  pre_bootstrap_user_data                = var.pre_bootstrap_user_data
  protect_from_scale_in                  = var.protect_from_scale_in
  ram_disk_id                            = var.ram_disk_id
  schedules                              = var.schedules
  security_group_description             = var.security_group_description
  security_group_name                    = var.security_group_name
  security_group_rules                   = var.security_group_rules
  security_group_tags                    = var.security_group_tags
  security_group_use_name_prefix         = var.security_group_use_name_prefix
  service_linked_role_arn                = var.service_linked_role_arn
  subnet_ids                             = var.subnet_ids
  suspended_processes                    = var.suspended_processes
  tags                                   = var.tags
  target_group_arns                      = var.target_group_arns
  termination_policies                   = var.termination_policies
  update_launch_template_default_version = var.update_launch_template_default_version
  use_mixed_instances_policy             = var.use_mixed_instances_policy
  use_name_prefix                        = var.use_name_prefix
  user_data_template_path                = var.user_data_template_path
  vpc_id                                 = var.vpc_id
  vpc_security_group_ids                 = var.vpc_security_group_ids
  wait_for_capacity_timeout              = var.wait_for_capacity_timeout
  wait_for_elb_capacity                  = var.wait_for_elb_capacity
  warm_pool                              = var.warm_pool
}
