module "route53_resolver-endpoints" {
  source                             = "terraform-aws-modules/route53/aws//modules/resolver-endpoints"
  version                            = "4.1.0"
  create                             = var.create
  create_security_group              = var.create_security_group
  direction                          = var.direction
  ip_address                         = var.ip_address
  name                               = var.name
  protocols                          = var.protocols
  security_group_description         = var.security_group_description
  security_group_egress_cidr_blocks  = var.security_group_egress_cidr_blocks
  security_group_ids                 = var.security_group_ids
  security_group_ingress_cidr_blocks = var.security_group_ingress_cidr_blocks
  security_group_name                = var.security_group_name
  security_group_name_prefix         = var.security_group_name_prefix
  security_group_tags                = var.security_group_tags
  subnet_ids                         = var.subnet_ids
  tags                               = var.tags
  type                               = var.type
  vpc_id                             = var.vpc_id
}
