module "iam_iam-assumable-role" {
  source                        = "terraform-aws-modules/iam/aws//modules/iam-assumable-role"
  version                       = "0.5.0"
  admin_role_policy_arn         = var.admin_role_policy_arn
  attach_admin_policy           = var.attach_admin_policy
  attach_poweruser_policy       = var.attach_poweruser_policy
  attach_readonly_policy        = var.attach_readonly_policy
  create_role                   = var.create_role
  custom_role_policy_arns       = var.custom_role_policy_arns
  max_session_duration          = var.max_session_duration
  mfa_age                       = var.mfa_age
  poweruser_role_policy_arn     = var.poweruser_role_policy_arn
  readonly_role_policy_arn      = var.readonly_role_policy_arn
  role_name                     = var.role_name
  role_path                     = var.role_path
  role_permissions_boundary_arn = var.role_permissions_boundary_arn
  role_requires_mfa             = var.role_requires_mfa
  trusted_role_arns             = var.trusted_role_arns
}
