module "redshift" {
  source                              = "terraform-aws-modules/redshift/aws"
  version                             = "1.0.0"
  automated_snapshot_retention_period = var.automated_snapshot_retention_period
  cluster_database_name               = var.cluster_database_name
  cluster_iam_roles                   = var.cluster_iam_roles
  cluster_identifier                  = var.cluster_identifier
  cluster_master_password             = var.cluster_master_password
  cluster_master_username             = var.cluster_master_username
  cluster_node_type                   = var.cluster_node_type
  cluster_number_of_nodes             = var.cluster_number_of_nodes
  cluster_parameter_group             = var.cluster_parameter_group
  cluster_port                        = var.cluster_port
  cluster_version                     = var.cluster_version
  encrypted                           = var.encrypted
  kms_key_id                          = var.kms_key_id
  parameter_group_name                = var.parameter_group_name
  preferred_maintenance_window        = var.preferred_maintenance_window
  publicly_accessible                 = var.publicly_accessible
  redshift_subnet_group_name          = var.redshift_subnet_group_name
  skip_final_snapshot                 = var.skip_final_snapshot
  subnets                             = var.subnets
  tags                                = var.tags
  vpc_security_group_ids              = var.vpc_security_group_ids
  wlm_json_configuration              = var.wlm_json_configuration
}
